import { GoogleGenAI } from "@google/genai";

export type RefinementPreset = 'vector' | 'high-contrast' | 'accessible-color' | 'dark-mode' | 'custom';

export interface RefinementOptions {
  preset?: RefinementPreset;
  customPrompt?: string;
  model?: 'gemini-3.1-flash-image' | 'gemini-3.1-flash-lite-image';
  aspectRatio?: '1:1' | '3:4' | '4:3' | '16:9' | '9:16';
}

const PRESET_PROMPTS: Record<Exclude<RefinementPreset, 'custom'>, string> = {
  'vector': 'Re-render this handwritten or scanned mathematical diagram into a pristine, high-contrast, clean vector line-art illustration on a pure white background. Preserve all axes, curves, geometric shapes, labels, and mathematical symbols accurately while removing paper smudges and handwriting noise.',
  'high-contrast': 'Clean up and enhance this mathematical figure. Remove all paper texture, shadows, and background noise. Sharpen all lines, curves, arrows, and labels to achieve high contrast and maximum readability for low-vision readers.',
  'accessible-color': 'Re-render this diagram with a high-contrast, color-blind friendly color palette. Use distinct line patterns (dashed, solid, dotted) and distinct WCAG-compliant colors for different curves and shapes. Ensure all text labels and equations remain crystal clear.',
  'dark-mode': 'Convert this mathematical diagram into a dark-theme high-contrast graphic on a deep dark canvas with bright white or neon accent vector lines and clear text labels.'
};

/**
 * Refines or cleans up a diagram/figure using Gemini image editing capabilities (gemini-3.1-flash-image).
 */
export async function refineDiagramWithGemini(
  base64Image: string,
  options: RefinementOptions = {}
): Promise<{ imageUrl: string; tokenCount: number; modelUsed: string }> {
  const apiKey = process.env.GEMINI_API_KEY;
  if (!apiKey) {
    throw new Error("GEMINI_API_KEY environment variable is missing.");
  }

  const ai = new GoogleGenAI({
    apiKey,
    httpOptions: {
      headers: {
        'User-Agent': 'aistudio-build',
      }
    }
  });

  // Extract raw base64 data and mimeType
  let rawBase64 = base64Image;
  let mimeType = 'image/png';
  
  if (base64Image.startsWith('data:')) {
    const matches = base64Image.match(/^data:(image\/[a-zA-Z+]+);base64,(.+)$/);
    if (matches && matches.length === 3) {
      mimeType = matches[1];
      rawBase64 = matches[2];
    } else {
      rawBase64 = base64Image.split(',')[1] || base64Image;
    }
  }

  // Construct prompt
  const preset = options.preset || 'vector';
  const instruction = preset === 'custom' && options.customPrompt
    ? options.customPrompt
    : PRESET_PROMPTS[preset as Exclude<RefinementPreset, 'custom'>] || PRESET_PROMPTS['vector'];

  const promptText = `${instruction}\n\nCRITICAL INSTRUCTIONS:\n1. Keep all mathematical meaning, equations, labels, variables, and axis values identical.\n2. Do NOT hallucinate new elements or change the topology/curves.\n3. Return a clean, complete image.`;

  const primaryModel = options.model || 'gemini-3.1-flash-lite-image';
  const fallbackModel = 'gemini-3.1-flash-image';

  const tryModel = async (selectedModel: string) => {
    const response = await ai.models.generateContent({
      model: selectedModel,
      contents: {
        parts: [
          {
            inlineData: {
              data: rawBase64,
              mimeType: mimeType,
            },
          },
          {
            text: promptText,
          },
        ],
      },
      config: {
        imageConfig: {
          aspectRatio: options.aspectRatio || "1:1",
          imageSize: "1K"
        }
      }
    });

    const candidates = response.candidates;
    if (!candidates || candidates.length === 0) {
      throw new Error("No image generated by Gemini.");
    }

    const parts = candidates[0].content?.parts || [];
    for (const part of parts) {
      if (part.inlineData && part.inlineData.data) {
        const outMime = part.inlineData.mimeType || 'image/png';
        const outBase64 = part.inlineData.data;
        const imageUrl = `data:${outMime};base64,${outBase64}`;
        const tokenCount = response.usageMetadata?.totalTokenCount || 0;
        return { imageUrl, tokenCount, modelUsed: selectedModel };
      }
    }

    throw new Error("Gemini response contained no inline image data.");
  };

  try {
    return await tryModel(primaryModel);
  } catch (err: any) {
    console.warn(`Refinement with ${primaryModel} failed. Attempting fallback to ${fallbackModel}:`, err);
    try {
      return await tryModel(fallbackModel);
    } catch (fallbackErr: any) {
      console.error(`Refinement fallback failed:`, fallbackErr);
      throw new Error(`Diagram refinement failed: ${fallbackErr.message || err.message}`);
    }
  }
}
